### ISSUE TITLE
Crash after displaying mapWize Map

### ISSUE THREAD

**Issue by samy-baili** [Mapwize/mapwize-app-android#2]
`
java.lang.NoSuchMethodError: No virtual method add(Lio/realm/RealmModel;)Z in class Lio/realm/RealmList; or its super classes (declaration of 'io.realm.RealmList' appears in /data/app/-PXK5Sc96avizHEP-NNXgsA==/base.apk:classes52.dex)
                                                                             at io.mapwize.mapwizeformapbox.api.Parser.b(Unknown Source:28)
                                                                             at io.mapwize.mapwizeformapbox.api.Parser.a(Unknown Source:117)
                                                                             at io.mapwize.mapwizeformapbox.api.Parser.a(Unknown Source:21)
                                                                             at io.mapwize.mapwizeformapbox.api.Api$25.a(Unknown Source:0)
                                                                             at io.mapwize.mapwizeformapbox.api.Api$25.parse(Unknown Source:0)
                                                                             at io.mapwize.mapwizeformapbox.api.internal.ApiCallbackHelper.onResponse(Unknown Source:43)
                                                                             at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                             at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                             at java.lang.Thread.run(Thread.java:764)
`

**Comment by emerciercontexeo** [comment]
Hello @samy-baili,

Can you give me more information about what you are doing when the crash occurs ?

**Comment by emerciercontexeo** [comment]
Are you using Realm in your application ?

**Comment by samy-baili** [comment]
Yes I am using Realm. When I am opening the MapActivity, the map is displayed during few seconds and the app crash

**Comment by samy-baili** [comment]
Wich Realm version are you using ? May be it's because we are not using the same version...

**Comment by emerciercontexeo** [comment]
Ok, I can reproduce the same error using a Application with another version of realm that the one embedded in MapwizePlugin.

The version of Realm is 3.0.0 in the SDK.

What's yours ?

**Comment by samy-baili** [comment]
The latest => 4.3.3

**Comment by emerciercontexeo** [comment]
Ok thanks.

I will make some modification to avoid this conflict. I keep you in touch quickly.

**Comment by emerciercontexeo** [comment]
Hi @samy-baili ,

The version 1.0.6 has been release. It's solve the issue. Thanks for reporting.
