### ISSUE TITLE
Screen showing black, app crashing on autocomplete item click!

### ISSUE THREAD

**Issue by kaushik-mota** [Mapwize/mapwize-app-android#5]
I am trying to run this app and getting weird issue of black screen and some UI elements overlapping each other.
I have added API KEY in `MapwizeApplication` class as well.
App is also crashing when selecting item from search autocomplete dropdown with below crash log :
```
25380-25380/io.mapwize.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.mapwize.app, PID: 25380
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.mapboxsdk.camera.CameraPosition com.mapbox.mapboxsdk.maps.MapboxMap.getCameraForLatLngBounds(com.mapbox.mapboxsdk.geometry.LatLngBounds, int[])' on a null object reference
        at com.mapbox.mapboxsdk.camera.CameraUpdateFactory$CameraBoundsUpdate.getCameraPosition(CameraUpdateFactory.java:241)
        at io.mapwize.mapwizeformapbox.MapwizePlugin.centerOnVenue(Unknown Source:48)
        at io.mapwize.app.MapActivity.closeSearch(MapActivity.java:577)
        at io.mapwize.app.MapActivity.onItemSelected(MapActivity.java:569)
        at io.mapwize.app.SearchResultsListAdapter$SearchItemViewHolder$1.onClick(SearchResultsListAdapter.java:155)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24712)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:6565)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

```
versionCode 305022
versionName "3.5.2"
```
**UI issue :**
![device-2018-09-24-173948](https://user-images.githubusercontent.com/10348357/45951984-2b70c800-c023-11e8-9b98-1a7699fb4b46.png)

**API Key Added :**
![img-2018-09-24_17 40 25](https://user-images.githubusercontent.com/10348357/45951985-2b70c800-c023-11e8-8c3b-41ba9290b83d.png)

**Device Information:**
![device-2018-09-24-180006](https://user-images.githubusercontent.com/10348357/45952138-af2ab480-c023-11e8-88dc-2e72f36f2193.png)

**Comment by emerciercontexeo** [comment]
This sounds to be the same issue that MapwizeSimpleAppAndroid.

Did you set the api key in the activity_main.xml ?

Actually, you have to set ApiKey in Application class and in the layout file.
app:mapbox_styleUrl="https://outdoor.mapwize.io/styles/mapwize/style.json?key=YOU_MAPWIZE_API_KEY"/>

This allows mapbox sdk to load our map style.

I know that is not really developer friendly but I am working on it.

I am also working on the UI to improve it and avoid glitches.

**Comment by emerciercontexeo** [comment]
For the crash, the problem here is that the map is not loaded and performing a search ask the map to center on a venue.
I will had guard to avoid crash but it is most an issue about loading the map.

**Comment by kaushik-mota** [comment]
@emerciercontexeo Thank you for the quick feedback. I will do these changes and check the app.

**Comment by kaushik-mota** [comment]
Thank you, it's working now.
